import requests
import datetime as dt
import os


# ----------------------- Personal Metrics -----------------------
GENDER = str  # male/female
WEIGHT_KG = int  # add your info
HEIGHT_CM = int  # add your info
AGE = int  # add your info


# ----------------------- NutritionIX API Request -----------------------
# must sign up for a free account to get API info
APP_ID = os.environ["APP_ID"]  # add your API id
API_KEY = os.environ["API_KEY"]  # add your API key

exercise_endpoint = "https://trackapi.nutritionix.com/v2/natural/exercise"
header = {
    "x-app-id": APP_ID,
    "x-app-key": API_KEY,
    "Content-Type": "application/json"
}

params = {
    "query": str(input("What exercise did you do? ")),
    "gender": GENDER,
    "weight_kg": WEIGHT_KG,
    "height_cm": HEIGHT_CM,
    "age": AGE
}

response = requests.post(url=exercise_endpoint, json=params, headers=header)
result = response.json()
input_exercise = result['exercises'][0]['user_input']
input_duration = result['exercises'][0]['duration_min']
input_calories = result['exercises'][0]['nf_calories']


# -------------------- Date/Time --------------------
input_date = dt.datetime.now().strftime("%m/%d/%Y")  # today's date
input_time = dt.datetime.now().strftime("%H:%M:%S")  # current time


# -------------------- Sheety API Request --------------------
# must sign up for a free account to get API info
SHEETY_ENPOINT = os.environ["SHEETY_ENPOINT"]  # must create/open sheet in Sheety to find autogenerated API endpoint

# enable basic authentication then add base64 encoded pass
BASE_64_PASS = os.environ["BASE_64_PASS"]  # add it here, or replace in fstr
header = {
    "Authorization": f"Basic {BASE_64_PASS}"
}

sheety_params = {
    "sheet1": {
        "date": f"{input_date}",
        "time": f"{input_time}",
        "exercise": f"{input_exercise}",
        "duration": f"{input_duration}",
        "calories": f"{input_calories}"
    }
}
sheet_resp = requests.post(url=SHEETY_ENPOINT, json=sheety_params, headers=header)
print(sheet_resp.text)
